export const Users = [
    {
      id:1,
      profilePicture: "assets/person/1.jpg",
      username: "Imam Muslim",
    },
    {
      id:2,
      profilePicture: "assets/person/2.jpg",
      username: "Julian Jono",
    },
    {
      id:3,
      profilePicture: "assets/person/3.jpg",
      username: "Parjo Putune Mbah Dul",
    },
    {
      id:4,
      profilePicture: "assets/person/4.jpg",
      username: "Zulfikar Assaud",
    },
    {
      id:5,
      profilePicture: "assets/person/5.jpg",
      username: "Hans Fatta",
    },
    {
      id:6,
      profilePicture: "assets/person/6.jpg",
      username: "Mugiwara no Luffy",
    },
    {
      id:7,
      profilePicture: "assets/person/7.jpg",
      username: "Fino Style",
    },
    {
      id:8,
      profilePicture: "assets/person/8.jpg",
      username: "Joko Surapto",
    },
    {
      id:9,
      profilePicture: "assets/person/9.jpg",
      username: "Zahra Puspita",
    },
    {
      id:10,
      profilePicture: "assets/person/10.jpg",
      username: "Zafar Harley",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Hiduplah dengan damai & berdamailah dengan hidup.",
      photo: "assets/post/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
      share: 2,
      save: 5,
    },
    {
      id: 2,
      desc: "No Excuse",
      photo: "assets/post/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
      share: 0,
      save: 3,
    },
    {
      id: 3,
      desc: "Pagimu pagiku juga.",
      photo: "assets/post/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
      share: 20,
      save: 10,
    },
    {
      id: 4,
      desc: "Belajarlah bela diri, karena you'll fight alone, nobody will freely help you. Join sasana tinju kami : Jl.puro asri km 8,kel. Sumberdana, kec. Tanjungkali, Jogja",
      photo: "assets/post/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
      share: 9,
      save: 7,
    },
    {
      id: 5,
      desc: "Gimana Final Project nya? aman?",
      photo: "assets/post/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
      share: 0,
      save: 0,
    },
    {
      id: 6,
      desc: "Bila kamu lapar makanlah.",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
      share: 4,
      save: 4,
    },
    {
      id: 7,
      desc: "tak ada hasil tanpa proses, bro its your turn!!.",
      photo: "assets/post/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
      share: 2,
      save: 5,
    },
    {
      id: 8,
      photo: "assets/post/8.jpg",
      desc: "Besok uda UAS aja nih, Ngopi dulu nggak sih....",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
      share: 1,
      save: 8,
    },
    {
      id: 9,
      desc: "Sudah dibungkus, Siap diangkut.",
      photo: "assets/post/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
      share: 5,
      save: 2,
    },
    {
      id: 10,
      desc: "Ini motorku, Mana motormu?.",
      photo: "assets/post/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
      share: 1,
      save: 1,
    },
  ];
  export const Tags = [
    {
      tagName: "Hogwarts Legacy",
      count: 550.000,
    },
    {
      tagName: "Politics",
      count: 520.000,
    },
    {
      tagName: "Japan",
      count: 350.000,
    },
    {
      tagName: "Ohio",
      count: 270.000,
    },
    {
      tagName: "Gaming",
      count: 50.000,
    }
  ];